// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WB.Data;

#nullable disable

namespace WB.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.1.23111.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WB.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Categories1");
                });

            modelBuilder.Entity("WB.Models.ScanLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductionDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ScanDate")
                        .HasColumnType("date");

                    b.Property<string>("ScanTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ScanLog");
                });

            modelBuilder.Entity("WB.Models.state_change", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("change_state");
                });

            modelBuilder.Entity("WB_Api.Models.ScannerDTO", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ScannerDTOid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("batchNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("plc_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pn_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prodDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("scan_value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("ScannerDTOid");

                    b.ToTable("scanner");
                });

            modelBuilder.Entity("WB_Api.Models.ScannerDTO", b =>
                {
                    b.HasOne("WB_Api.Models.ScannerDTO", null)
                        .WithMany("Scanners")
                        .HasForeignKey("ScannerDTOid");
                });

            modelBuilder.Entity("WB_Api.Models.ScannerDTO", b =>
                {
                    b.Navigation("Scanners");
                });
#pragma warning restore 612, 618
        }
    }
}
